# Generated by Django 4.2.25 on 2025-10-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video for hero carousel (MP4/WebM)', null=True, upload_to='banners/videos/'),
        ),
    ]
