# Generated by Django 4.2.25 on 2025-10-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for hero carousel', null=True, upload_to='banners/'),
        ),
    ]
