# Generated by Django 4.2.25 on 2025-10-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscriber'),
        ('core', '0003_alter_banner_image'),
    ]

    operations = [
    ]
