# Generated by Django 4.2.25 on 2025-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='notify_users',
            field=models.BooleanField(default=False, help_text='Notify users when this offer is added'),
        ),
    ]
