# Generated by Django 4.2.25 on 2025-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_best_seller_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_display',
            field=models.BooleanField(default=False, help_text='Show this category on home page'),
        ),
    ]
