# Generated by Django 4.2.25 on 2025-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optional image URL for category thumbnail on home'),
        ),
    ]
