# Generated by Django 4.2.25 on 2025-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload thumbnail for home chips', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='(Optional) External image URL for thumbnail on home'),
        ),
    ]
