# Generated by Codex CLI: add product/variant shipping attributes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_category_thumbnail_alter_category_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=3, help_text="Weight per unit in kg"),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package length in cm"),
        ),
        migrations.AddField(
            model_name="product",
            name="breadth_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package breadth in cm"),
        ),
        migrations.AddField(
            model_name="product",
            name="height_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package height in cm"),
        ),
        migrations.AddField(
            model_name="variant",
            name="weight_kg",
            field=models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=3, help_text="Weight per unit in kg"),
        ),
        migrations.AddField(
            model_name="variant",
            name="length_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package length in cm"),
        ),
        migrations.AddField(
            model_name="variant",
            name="breadth_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package breadth in cm"),
        ),
        migrations.AddField(
            model_name="variant",
            name="height_cm",
            field=models.PositiveIntegerField(null=True, blank=True, help_text="Package height in cm"),
        ),
    ]

