# Generated by Codex CLI - add cost_price to Variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_variant_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='cost_price',
            field=models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2),
        ),
    ]

