# Generated by Django 4.2.25 on 2025-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_variant_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notify_users',
            field=models.BooleanField(default=False, help_text='Notify users about this product'),
        ),
    ]
