# Generated by Django 4.2.25 on 2025-10-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
