# Generated by Django 4.2.25 on 2025-10-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_variant_retail_prices'),
        ('catalog', '0010_alter_variant_color'),
    ]

    operations = [
    ]
