# Generated by Codex CLI - add return/exchange models and statuses
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_coupon_code_order_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("return_requested", "Return requested"),
                    ("exchange_requested", "Exchange requested"),
                    ("return_in_transit", "Return in transit"),
                    ("return_completed", "Return completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("return", "Return"), ("exchange", "Exchange")], max_length=10)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("pickup_scheduled", "Pickup scheduled"),
                    ("in_transit", "In transit"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ], default="requested", max_length=20)),
                ("awb_code", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="returns", to="orders.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="auth.user")),
            ],
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("exchange_variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="catalog.variant")),
                ("order_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orders.orderitem")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.returnrequest")),
            ],
        ),
    ]

