# Generated by Codex CLI - add amazon-like statuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_return_models_and_statuses.py".replace('.py','')),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Placed"),
                    ("paid", "Paid"),
                    ("confirmed", "Confirmed"),
                    ("packed", "Packed"),
                    ("dispatched", "Dispatched"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("return_requested", "Return requested"),
                    ("exchange_requested", "Exchange requested"),
                    ("return_in_transit", "Return in transit"),
                    ("return_completed", "Return completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]

