# Generated by Codex CLI - add cost fields to OrderItem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_amazon_like_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(default=0, max_digits=10, decimal_places=2),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_cost',
            field=models.DecimalField(default=0, max_digits=10, decimal_places=2),
        ),
    ]

