# Generated by Django 4.2.25 on 2025-10-31 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variant_snapshots'),
        ('orders', '0005_item_cost_fields'),
    ]

    operations = [
    ]
