# Generated by Django 4.2.25 on 2025-10-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20251031_0917'),
        ('orders', '0006_order_stock_debited'),
    ]

    operations = [
    ]
